from __future__ import annotations

import dataclasses
import json
import os
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Literal

from common.tradinghub_order_callback import XianyuOrderEvent, build_payload, post_order_callback


LoginStatus = Literal["not_logged_in", "waiting_scan", "logged_in", "expired"]
WorkerStatus = Literal["stopped", "running"]


@dataclasses.dataclass
class ControlConfig:
    auto_reply_enabled: bool = False
    auto_delivery_enabled: bool = False
    refund_callback_enabled: bool = True
    product_slug: str = "riskmanager"


@dataclasses.dataclass
class ControlState:
    login_status: LoginStatus = "not_logged_in"
    worker_status: WorkerStatus = "stopped"
    qr_content: str | None = None
    qr_image_url: str | None = None
    qr_session_id: str | None = None
    config: ControlConfig = dataclasses.field(default_factory=ControlConfig)
    recent_messages: list[dict[str, Any]] = dataclasses.field(default_factory=list)
    recent_events: list[dict[str, Any]] = dataclasses.field(default_factory=list)


state = ControlState(
    config=ControlConfig(product_slug=os.getenv("PRODUCT_SLUG", "riskmanager").strip() or "riskmanager")
)
worker_stop_event = threading.Event()
worker_thread: threading.Thread | None = None
managed_processes: dict[str, subprocess.Popen[Any]] = {}


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SERVICE_PORTS = {
    "backend_web": int(os.getenv("BACKEND_WEB_PORT", "8089")),
    "websocket": int(os.getenv("WEBSOCKET_PORT", "8090")),
    "scheduler": int(os.getenv("SCHEDULER_PORT", "8091")),
}
PAID_STATUSES = {"paid", "pending_ship", "to_ship", "wait_seller_send_goods", "shipped", "completed", "success"}
REFUNDED_STATUSES = {"refunded", "refund", "refund_success", "refund_completed", "after_sale_success"}
CANCELLED_STATUSES = {"cancelled", "canceled", "closed", "trade_closed", "buyer_cancelled"}


def now_ms() -> int:
    return int(time.time() * 1000)


def record_message(message: str, payload: dict[str, Any] | None = None) -> None:
    state.recent_messages.insert(
        0,
        {
            "id": f"msg-{now_ms()}",
            "type": "dry_run_message",
            "message": message,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "payload": payload or {},
        },
    )
    del state.recent_messages[20:]


def record_event(event_type: str, external_order_id: str, payload: dict[str, Any]) -> None:
    state.recent_events.insert(
        0,
        {
            "id": f"evt-{now_ms()}",
            "event_type": event_type,
            "external_order_id": external_order_id,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "payload": payload,
        },
    )
    del state.recent_events[20:]


def config_dict() -> dict[str, Any]:
    return dataclasses.asdict(state.config)


def status_dict(message: str = "") -> dict[str, Any]:
    service_status = get_service_status()
    state.worker_status = "running" if service_status["websocket"] and service_status["scheduler"] else "stopped"
    return {
        "ok": True,
        "status": state.login_status,
        "login_status": state.login_status,
        "worker": state.worker_status,
        "services": service_status,
        "message": message,
        "qr_content": state.qr_content,
        "qr_image_url": state.qr_image_url,
        "qr_session_id": state.qr_session_id,
        "config": config_dict(),
        "recent_messages": state.recent_messages,
        "recent_events": state.recent_events,
    }


def start_login() -> dict[str, Any]:
    state.login_status = "not_logged_in"
    state.qr_session_id = None
    state.qr_image_url = None
    state.qr_content = None

    backend_result = request_backend_qr_login()
    state.login_status = "waiting_scan"

    if backend_result.get("ok"):
        state.qr_session_id = str(backend_result.get("session_id") or "")
        state.qr_image_url = str(backend_result.get("qr_code_url") or "") or None
        state.qr_content = None
        record_message("Xianyu login QR generated by backend adapter.", {"session_id": state.qr_session_id})
        return status_dict("Xianyu QR login generated.")

    state.qr_session_id = None
    state.qr_image_url = None
    state.qr_content = str(backend_result.get("message") or "Xianyu QR login backend is not connected.")
    record_message("Xianyu login QR request failed.", backend_result)
    return status_dict(state.qr_content)


def refresh_login_status() -> dict[str, Any]:
    if not state.qr_session_id:
        return status_dict()

    backend_result = request_backend_qr_status(state.qr_session_id)
    status = str(backend_result.get("status") or "")

    if status in {"success", "logged_in", "already_processed"}:
        state.login_status = "logged_in"
    elif status in {"expired", "failed", "cancelled", "error"}:
        state.login_status = "expired"
    elif status in {"waiting", "scanned", "processing", "pending"}:
        state.login_status = "waiting_scan"

    return status_dict(str(backend_result.get("message") or ""))


def clear_activity() -> dict[str, Any]:
    state.recent_messages.clear()
    state.recent_events.clear()
    return status_dict("Xianyu dry-run logs and order events cleared.")


def is_port_open(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.4)
        return sock.connect_ex((host, port)) == 0


def get_service_status() -> dict[str, bool]:
    return {name: is_port_open(port) for name, port in SERVICE_PORTS.items()}


def local_service_env() -> dict[str, str]:
    env = os.environ.copy()
    defaults = {
        "ENVIRONMENT": "development",
        "LOG_LEVEL": "INFO",
        "MYSQL_HOST": "localhost",
        "MYSQL_PORT": "3306",
        "MYSQL_DATABASE": "xianyu_auto_reply",
        "REDIS_HOST": "localhost",
        "REDIS_PORT": "6379",
        "REDIS_DB": "0",
        "BACKEND_WEB_SERVICE_URL": f"http://localhost:{SERVICE_PORTS['backend_web']}",
        "WEBSOCKET_SERVICE_URL": f"http://localhost:{SERVICE_PORTS['websocket']}",
        "STATIC_DIR": "static",
        "BROWSER_HEADLESS": "true",
        "WEBSOCKET_PORT": str(SERVICE_PORTS["websocket"]),
        "SCHEDULER_PORT": str(SERVICE_PORTS["scheduler"]),
    }
    for key, value in defaults.items():
        env.setdefault(key, value)
    return env


def start_python_service(name: Literal["websocket", "scheduler"], script_dir: str) -> dict[str, Any]:
    port = SERVICE_PORTS[name]
    if is_port_open(port):
        return {"ok": True, "service": name, "already_running": True, "port": port}

    logs_dir = Path(os.getenv("XIANYU_CONTROL_LOG_DIR", str(Path(os.getenv("TEMP", ".")))))
    stdout_path = logs_dir / f"xianyu-{name}-managed.out.log"
    stderr_path = logs_dir / f"xianyu-{name}-managed.err.log"
    stdout = stdout_path.open("ab")
    stderr = stderr_path.open("ab")
    creationflags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
    process = subprocess.Popen(
        [sys.executable, "main.py"],
        cwd=str(PROJECT_ROOT / script_dir),
        env=local_service_env(),
        stdout=stdout,
        stderr=stderr,
        creationflags=creationflags,
    )
    managed_processes[name] = process

    for _ in range(30):
        if is_port_open(port):
            return {"ok": True, "service": name, "pid": process.pid, "port": port}
        if process.poll() is not None:
            return {
                "ok": False,
                "service": name,
                "error": "SERVICE_EXITED",
                "returncode": process.returncode,
                "stderr_log": str(stderr_path),
            }
        time.sleep(0.5)

    return {"ok": False, "service": name, "error": "SERVICE_START_TIMEOUT", "pid": process.pid, "port": port}


def stop_port(port: int) -> None:
    if os.name != "nt":
        return
    subprocess.run(
        [
            "powershell",
            "-NoProfile",
            "-Command",
            (
                f"Get-NetTCPConnection -LocalPort {port} -ErrorAction SilentlyContinue | "
                "Select-Object -ExpandProperty OwningProcess -Unique | "
                "ForEach-Object { Stop-Process -Id $_ -Force }"
            ),
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


def db_connect():
    import pymysql

    return pymysql.connect(
        host=os.getenv("MYSQL_HOST", "localhost"),
        port=int(os.getenv("MYSQL_PORT", "3306")),
        user=os.getenv("MYSQL_USER", ""),
        password=os.getenv("MYSQL_PASSWORD", ""),
        database=os.getenv("MYSQL_DATABASE", "xianyu_auto_reply"),
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=True,
    )


def parse_metadata(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if not value:
        return {}
    try:
        parsed = json.loads(str(value))
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        return {}


def select_pending_order_callbacks(limit: int = 20) -> list[dict[str, Any]]:
    with db_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                select id, order_no, status, buyer_nick, buyer_id, chat_id, item_id,
                       quantity, amount, currency, account_id, metadata, placed_at
                from xy_orders
                order by updated_at asc
                limit %s
                """,
                (limit,),
            )
            return list(cursor.fetchall())


def update_order_metadata(order_id: int, metadata: dict[str, Any], delivery_message: str | None = None) -> None:
    metadata_json = json.dumps(metadata, ensure_ascii=False, separators=(",", ":"))
    with db_connect() as conn:
        with conn.cursor() as cursor:
            if delivery_message:
                cursor.execute(
                    """
                    update xy_orders
                    set metadata=%s, delivery_method='tradinghub', delivery_content=%s
                    where id=%s
                    """,
                    (metadata_json, delivery_message, order_id),
                )
            else:
                cursor.execute("update xy_orders set metadata=%s where id=%s", (metadata_json, order_id))


def event_type_for_order(order: dict[str, Any], metadata: dict[str, Any]) -> str | None:
    status = str(order.get("status") or "").lower()
    sent = metadata.get("tradinghub_callback", {})
    paid_sent = bool(isinstance(sent, dict) and sent.get("paid"))

    if status in PAID_STATUSES and not paid_sent:
        return "paid"
    if status in REFUNDED_STATUSES and state.config.refund_callback_enabled:
        if not (isinstance(sent, dict) and sent.get("refunded")):
            return "refunded"
    if status in CANCELLED_STATUSES:
        if paid_sent and state.config.refund_callback_enabled and not (isinstance(sent, dict) and sent.get("refunded")):
            return "refunded"
        if not paid_sent and not (isinstance(sent, dict) and sent.get("cancelled")):
            return "cancelled"
    return None


def build_event_from_order(order: dict[str, Any], event_type: str) -> XianyuOrderEvent:
    amount = order.get("amount")
    return XianyuOrderEvent(
        event_type=event_type,  # type: ignore[arg-type]
        external_order_id=str(order.get("order_no") or order.get("id")),
        amount=float(amount) if amount is not None else 0,
        currency=str(order.get("currency") or "CNY"),
        quantity=int(order.get("quantity") or 1),
        buyer_contact=str(order.get("buyer_nick") or order.get("buyer_id") or ""),
        buyer={
            "buyer_id": order.get("buyer_id"),
            "buyer_nick": order.get("buyer_nick"),
            "chat_id": order.get("chat_id"),
            "account_id": order.get("account_id"),
        },
        metadata={
            "source": "xianyu_real_worker",
            "xianyu_order_id": order.get("id"),
            "xianyu_status": order.get("status"),
            "item_id": order.get("item_id"),
            "chat_id": order.get("chat_id"),
            "account_id": order.get("account_id"),
            "placed_at": str(order.get("placed_at") or ""),
        },
    )


def mark_callback_result(order: dict[str, Any], event_type: str, callback_result: dict[str, Any]) -> None:
    metadata = parse_metadata(order.get("metadata"))
    callbacks = metadata.get("tradinghub_callback")
    if not isinstance(callbacks, dict):
        callbacks = {}
    callbacks[event_type] = {
        "ok": bool(callback_result.get("ok")),
        "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "order_status": callback_result.get("order_status"),
        "license_status": callback_result.get("license_status"),
        "error": callback_result.get("error"),
    }
    metadata["tradinghub_callback"] = callbacks
    delivery_message = callback_result.get("delivery_message")
    update_order_metadata(
        int(order["id"]),
        metadata,
        delivery_message if isinstance(delivery_message, str) and callback_result.get("ok") else None,
    )


def send_delivery_message_for_order(order: dict[str, Any], message: str) -> dict[str, Any]:
    return send_message_adapter(
        {
            "account_id": order.get("account_id"),
            "chat_id": order.get("chat_id"),
            "buyer_id": order.get("buyer_id"),
            "buyer_nick": order.get("buyer_nick"),
        },
        message,
        dry_run=False,
    )


def process_order_callbacks_once() -> None:
    for order in select_pending_order_callbacks():
        metadata = parse_metadata(order.get("metadata"))
        event_type = event_type_for_order(order, metadata)
        if not event_type:
            continue

        event = build_event_from_order(order, event_type)
        callback_payload = build_payload(event, product_slug=state.config.product_slug)
        record_event(event_type, event.external_order_id, callback_payload)
        callback_result = post_order_callback(event, product_slug=state.config.product_slug)
        mark_callback_result(order, event_type, callback_result)
        record_message("TradingHub order callback posted.", {"order_no": event.external_order_id, "event_type": event_type, "ok": callback_result.get("ok")})

        delivery_message = callback_result.get("delivery_message")
        if (
            event_type == "paid"
            and callback_result.get("ok")
            and state.config.auto_delivery_enabled
            and isinstance(delivery_message, str)
        ):
            send_result = send_delivery_message_for_order(order, delivery_message)
            record_message("TradingHub delivery message sent through Xianyu adapter.", send_result)


def worker_loop() -> None:
    interval = max(2, int(os.getenv("XIANYU_ORDER_BRIDGE_INTERVAL_SECONDS", "10")))
    while not worker_stop_event.is_set():
        try:
            process_order_callbacks_once()
        except Exception as exc:
            record_message("Xianyu order bridge failed.", {"error": type(exc).__name__, "message": str(exc)})
        worker_stop_event.wait(interval)


def request_backend_qr_login() -> dict[str, Any]:
    base_url = os.getenv("XIANYU_BACKEND_BASE_URL", "http://127.0.0.1:8089").strip().rstrip("/")
    token = os.getenv("XIANYU_BACKEND_TOKEN", "").strip()
    timeout_seconds = int(os.getenv("XIANYU_BACKEND_QR_TIMEOUT_SECONDS", "90"))
    url = f"{base_url}/api/v1/qr-login/generate"
    request = urllib.request.Request(
        url,
        data=b"{}",
        headers={
            "content-type": "application/json",
            **({"authorization": f"Bearer {token}"} if token else {}),
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        try:
            error_payload = json.loads(exc.read().decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            error_payload = {}
        return {
            "ok": False,
            "error": "XIANYU_QR_BACKEND_REJECTED",
            "message": str(error_payload.get("message") or f"QR backend returned HTTP {exc.code}."),
        }
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        return {
            "ok": False,
            "error": "XIANYU_QR_BACKEND_UNAVAILABLE",
            "message": f"Unable to reach Xianyu QR backend at {url}. Start backend-web or set XIANYU_BACKEND_BASE_URL. {exc}",
        }

    data = payload.get("data") if isinstance(payload, dict) else None
    if isinstance(data, dict) and payload.get("success") is not False:
        qr_code_url = data.get("qr_code_url")
        if isinstance(qr_code_url, str) and qr_code_url.startswith("/"):
            qr_code_url = f"{base_url}{qr_code_url}"
        return {
            "ok": True,
            "session_id": data.get("session_id"),
            "qr_code_url": qr_code_url,
        }

    return {
        "ok": False,
        "error": "XIANYU_QR_BACKEND_REJECTED",
        "message": str(payload.get("message") if isinstance(payload, dict) else "QR backend rejected request."),
    }


def request_backend_qr_status(session_id: str) -> dict[str, Any]:
    base_url = os.getenv("XIANYU_BACKEND_BASE_URL", "http://127.0.0.1:8089").strip().rstrip("/")
    token = os.getenv("XIANYU_BACKEND_TOKEN", "").strip()
    url = f"{base_url}/api/v1/qr-login/status/{session_id}"
    request = urllib.request.Request(
        url,
        headers={**({"authorization": f"Bearer {token}"} if token else {})},
        method="GET",
    )

    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        return {
            "ok": False,
            "status": state.login_status,
            "message": f"Unable to query Xianyu QR status. {exc}",
        }

    data = payload.get("data") if isinstance(payload, dict) else None
    if isinstance(data, dict):
        return {
            "ok": payload.get("success") is not False,
            "status": data.get("status"),
            "message": data.get("message") or payload.get("message"),
            "account_info": data.get("account_info"),
        }

    return {
        "ok": payload.get("success") is not False if isinstance(payload, dict) else False,
        "status": payload.get("status") if isinstance(payload, dict) else state.login_status,
        "message": payload.get("message") if isinstance(payload, dict) else "",
    }


def start_worker() -> dict[str, Any]:
    global worker_thread

    websocket_result = start_python_service("websocket", "websocket")
    scheduler_result = start_python_service("scheduler", "scheduler")

    worker_stop_event.clear()
    if worker_thread is None or not worker_thread.is_alive():
        worker_thread = threading.Thread(target=worker_loop, name="xianyu-order-bridge", daemon=True)
        worker_thread.start()

    state.worker_status = "running"
    record_message(
        "Xianyu real listener worker started.",
        {"websocket": websocket_result, "scheduler": scheduler_result, "order_bridge": True},
    )
    return status_dict("Worker started with real websocket, scheduler, and TradingHub order bridge.")


def stop_worker() -> dict[str, Any]:
    worker_stop_event.set()
    for name, process in list(managed_processes.items()):
        if process.poll() is None:
            process.terminate()
        managed_processes.pop(name, None)
    stop_port(SERVICE_PORTS["websocket"])
    stop_port(SERVICE_PORTS["scheduler"])
    state.worker_status = "stopped"
    record_message("Xianyu real listener worker stopped.")
    return status_dict("Worker stopped.")


def update_config(payload: dict[str, Any]) -> dict[str, Any]:
    for key in ("auto_reply_enabled", "auto_delivery_enabled", "refund_callback_enabled"):
        if key in payload:
            setattr(state.config, key, bool(payload[key]))

    if "product_slug" in payload and str(payload["product_slug"]) != "riskmanager":
        return {
            "ok": False,
            "error": "PRODUCT_NOT_SUPPORTED",
            "message": "Only product_slug=riskmanager is supported by this control service.",
        }

    state.config.product_slug = "riskmanager"
    record_message("Xianyu automation config updated.", config_dict())
    return {"ok": True, "config": config_dict()}


def send_message_adapter(buyer: dict[str, Any] | None, message: str, dry_run: bool = True) -> dict[str, Any]:
    payload = {
        "buyer": buyer or {},
        "message": message,
        "dry_run": dry_run,
    }
    if not dry_run:
        account_id = str((buyer or {}).get("account_id") or "")
        chat_id = str((buyer or {}).get("chat_id") or "")
        buyer_id = str((buyer or {}).get("buyer_id") or "")
        token = os.getenv("XIANYU_BACKEND_TOKEN", "").strip()
        base_url = os.getenv("XIANYU_BACKEND_BASE_URL", "http://127.0.0.1:8089").strip().rstrip("/")

        if account_id and chat_id and buyer_id and token:
            request = urllib.request.Request(
                f"{base_url}/api/v1/chat-new/send-message/{account_id}",
                data=json.dumps({"cid": chat_id, "toUserId": buyer_id, "text": message}, ensure_ascii=False).encode("utf-8"),
                headers={"content-type": "application/json", "authorization": f"Bearer {token}"},
                method="POST",
            )
            try:
                with urllib.request.urlopen(request, timeout=30) as response:
                    response_payload = json.loads(response.read().decode("utf-8"))
                record_message("Delivery message sent to Xianyu chat.", {"account_id": account_id, "chat_id": chat_id, "buyer_id": buyer_id})
                return {"ok": True, "sent": True, "dry_run": False, "response": response_payload}
            except Exception as exc:
                record_message("Delivery message send failed.", {"error": type(exc).__name__, "message": str(exc), **payload})
                return {"ok": False, "sent": False, "dry_run": False, "error": type(exc).__name__, "message": str(exc)}

        record_message("Delivery message could not be sent because account/chat fields or backend token are missing.", payload)
        return {"ok": False, "sent": False, "dry_run": False, "error": "MISSING_CHAT_CONTEXT"}

    record_message("Delivery message prepared for Xianyu chat.", payload)
    return {"ok": True, "sent": False, "dry_run": dry_run, "message": "Message send is a dry-run adapter."}


def dry_run_order_event(payload: dict[str, Any]) -> dict[str, Any]:
    event_type = str(payload.get("event_type", "paid"))
    if event_type not in {"paid", "refunded", "cancelled"}:
        return {"ok": False, "error": "INVALID_EVENT_TYPE", "message": "event_type must be paid/refunded/cancelled."}

    product_slug = str(payload.get("product_slug") or state.config.product_slug or "riskmanager")
    if product_slug != "riskmanager":
        return {
            "ok": False,
            "error": "PRODUCT_NOT_SUPPORTED",
            "message": "Only product_slug=riskmanager is supported.",
        }

    event = XianyuOrderEvent(
        event_type=event_type,  # type: ignore[arg-type]
        external_order_id=str(payload.get("external_order_id") or f"TEST-XIANYU-{now_ms()}"),
        amount=payload.get("amount", 0) if isinstance(payload.get("amount", 0), (int, float)) else 0,
        currency=str(payload.get("currency") or "CNY"),
        quantity=int(payload.get("quantity") or 1),
        buyer_contact=str(payload.get("buyer_contact") or ""),
        buyer=payload.get("buyer") if isinstance(payload.get("buyer"), dict) else {},
        refund_reason=str(payload.get("refund_reason") or "") or None,
        metadata={
            "source": "xianyu_control_dry_run",
            "buyer": payload.get("buyer") or {},
            **(payload.get("metadata") if isinstance(payload.get("metadata"), dict) else {}),
        },
    )
    callback_payload = build_payload(event, product_slug=product_slug)
    record_event(event.event_type, event.external_order_id, callback_payload)

    should_send = bool(payload.get("send"))
    result: dict[str, Any] = {
        "ok": True,
        "event_type": event.event_type,
        "payload": callback_payload,
        "callback_result": {
            "ok": True,
            "dry_run": True,
            "message": "TradingHub callback was not called. Pass send=true to post with HMAC.",
        },
        "delivery_message": None,
    }

    if should_send:
        callback_result = post_order_callback(event, product_slug=product_slug)
        result["callback_result"] = callback_result
        if event.event_type == "paid" and isinstance(callback_result, dict):
            delivery_message = callback_result.get("delivery_message")
            if isinstance(delivery_message, str) and state.config.auto_delivery_enabled:
                result["delivery_message"] = delivery_message
                result["send_result"] = send_message_adapter(payload.get("buyer") if isinstance(payload.get("buyer"), dict) else {}, delivery_message)

    return result
